#baseurl: /seek

current_seek_version: "1.10.0"
current_docker_tag: "1.10"

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

name: FAIRDOM
url: https://docs.seek4science.org
author: FAIRDOM