plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick

exclude:
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

permalink: /:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"