#baseurl: /seek

current_seek_version: "1.12.0"
current_docker_tag: "1.12"

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

name: FAIRDOM
url: https://help.datahub-test.elixir-belgium.org
author: FAIRDOM